image:
  repository: "eliminyro/pyapp"
  pullPolicy: "IfNotPresent"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullNameOverride: ""

replicaCount: 1

postgresql:
  enabled: true

  postgresPassword: "THECAK3ISAL13"

  auth:
    username: "chell"
    password: "THECAKEISALIE"
    database: "aperture"

  nameOverride: "pgsql"

  architecture: "replication"
  primary:
    persistence:
      enabled: true
      storageClass: ""
      accessMode: "ReadWriteOnce"
      size: "1Gi"
  
  readReplicas:
    replicaCount: 1
    persistence:
      enabled: true
      storageClass: ""
      accessMode: "ReadWriteOnce"
      size: "1Gi"

persistence:
  enabled: false

mail:
  box: ""
  passwd: ""
  server: "smtp.gmail.com"
  port: 587
  tls: true
  recipient: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
service:
  type: "ClusterIP"
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: "/"
          pathType: "ImplementationSpecific"
  tls: []

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
