---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "python-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "python-app.name" . }}
    helm.sh/chart: {{ include "python-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- $fullname := required "Please specify a PostgreSQL pod name/ instance IP" (include "python-app.postgresql" .) }}
  {{- $username := required "Please specify a PostgreSQL username" .Values.postgresql.auth.username }}
  {{- $password := required "Please specify a password for database user" .Values.postgresql.auth.password }}
  {{- $port := default 5432 .Values.postgresql.port }}
  {{- $dbname := required "Please specify a PostgreSQL database" .Values.postgresql.auth.database }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" $username $password $fullname $port $dbname | b64enc | quote }}

  {{- $box:= required "Please specify a mailbox for sending notifications from" .Values.mail.box }}
  {{- $passwd := required "Please specify the said mailbox password" .Values.mail.passwd }}
  {{- $mailserver := required "Please specify mail server for sending notifications" .Values.mail.server }}
  {{- $mailport := required "Please specify mail server port" .Values.mail.port }}
  {{- $mailtls := required "Please specify whether the mail server uses TLS" .Values.mail.tls }}
  {{- $recipient := required "Please specify the recipient for notifications" .Values.mail.recipient }}
  MAIL_USERNAME: {{ print $box | b64enc | quote }}
  MAIL_PASSWORD: {{ print $passwd | b64enc | quote }}
  MAIL_SERVER: {{ print $mailserver | b64enc | quote }}
  MAIL_PORT: {{ print $mailport | b64enc | quote }}
  MAIL_USE_TLS: {{ print  $mailtls | b64enc | quote }}
  MAIL_RECIPIENT: {{ print $recipient | b64enc | quote }}
